### ISSUE TITLE
Reshape error

### ISSUE THREAD

**Issue by chengjianhong** [JoHof/lungmask#12]
Hi,
Thanks for your excellent work, I used it to segment the lung, but the following error occurred:

```
Traceback (most recent call last):
  File "Lung_mask.py", line 133, in <module>
    save_lung_mask()
  File "Lung_mask.py", line 16, in save_lung_mask
    segmentation = mask.apply(input_image,model)
  File "/home/jhcheng/userfolder/Anaconda3/envs/py36/lib/python3.6/site-packages/lungmask/mask.py", line 62, in apply
    outmask = np.asarray([utils.reshape_mask(outmask[i], xnew_box[i], inimg_raw.shape[1:]) for i in range(outmask.shape[0])], dtype=np.uint8)
  File "/home/jhcheng/userfolder/Anaconda3/envs/py36/lib/python3.6/site-packages/lungmask/mask.py", line 62, in <listcomp>
    outmask = np.asarray([utils.reshape_mask(outmask[i], xnew_box[i], inimg_raw.shape[1:]) for i in range(outmask.shape[0])], dtype=np.uint8)
  File "/home/jhcheng/userfolder/Anaconda3/envs/py36/lib/python3.6/site-packages/lungmask/utils.py", line 79, in reshape_mask
    res[tbox[0]:tbox[2],tbox[1]:tbox[3]] = imgres
ValueError: could not broadcast input array from shape (26,871) into shape (26,803)

```

**Comment by JoHof** [comment]
Hi,

will thats weird. I am not sure how this could happen. Does it happen with every image you try or is it just one case?

**Comment by JoHof** [comment]
what shape does input_image have? `input_image.GetSize()`

**Comment by chengjianhong** [comment]
@JoHof I checked my input image. The image shape is (803,62,512) and its voxel dimension is 0.474x6.95x0.475.  This image is not consistent with my other images, I will exclude it.
![image](https://user-images.githubusercontent.com/12234973/78541238-e2a8ea80-7827-11ea-925a-1b42b42806ad.png)
