### ISSUE TITLE
ValueError: could not broadcast input array from shape (1989,4) into shape (1989,3)

### ISSUE THREAD

**Issue by Alymostafa** [JoHof/lungmask#19]
```
INFO:root:Load model
INFO:root:Read input: /content/covid-chestxray-dataset/images/01E392EE-69F9-4E33-BFCE-E5C968654078.jpeg
INFO:root:Infer lungmask
100% 75/75 [00:28<00:00,  2.60it/s]
0
Traceback (most recent call last):
  File "/usr/local/bin/lungmask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/lungmask/__main__.py", line 42, in main
    result = mask.apply(input_image, model, force_cpu=args.cpu, batch_size=batchsize, volume_postprocessing=not(args.nopostprocess))
  File "/usr/local/lib/python3.6/dist-packages/lungmask/mask.py", line 65, in apply
    [utils.reshape_mask(outmask[i], xnew_box[i], inimg_raw.shape[1:]) for i in range(outmask.shape[0])],
  File "/usr/local/lib/python3.6/dist-packages/lungmask/mask.py", line 65, in <listcomp>
    [utils.reshape_mask(outmask[i], xnew_box[i], inimg_raw.shape[1:]) for i in range(outmask.shape[0])],
  File "/usr/local/lib/python3.6/dist-packages/lungmask/utils.py", line 91, in reshape_mask
    res[tbox[0]:tbox[2], tbox[1]:tbox[3]] = imgres
ValueError: could not broadcast input array from shape (1989,4) into shape (1989,3)
```

**Comment by JoHof** [comment]
Hi Mostafa,

This is a segmentation tool for CT scans not for X-ray images. Also, the image needs to be encoded in Hounsfield Units which is probably not the case for data that you find on the internet and is stored as jpeg.

Best,
Johannes
