### ISSUE TITLE
Question about broken pipe error

### ISSUE THREAD

**Issue by hrktkhs** [JoHof/lungmask#38]
Hello, 
I installed lungmask and try to run it but got the error below.
Could you help me to solve this problem?
I am using WIndows without GPU. 

INFO:root:No GPU support available, will use CPU. Note, that this is significantly slower!
  0%|          | 0/102 [00:00<?, ?it/s]
Traceback (most recent call last):

  File "C:\Users\.spyder-py3\COVID.py", line 16, in <module>
    segmentation = mask.apply(input_image)  # default model is U-net(R231)

  File "C:\Users\Anaconda3\lib\site-packages\lungmask\mask.py", line 64, in apply
    for X in tqdm(dataloader_val):

  File "C:\Users\Anaconda3\lib\site-packages\tqdm\std.py", line 1129, in __iter__
    for obj in iterable:

  File "C:\Users\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()

  File "C:\Users\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)

  File "C:\Users\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()

  File "C:\Users\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)

  File "C:\Users\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "C:\Users\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "C:\Users\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)

  File "C:\Users\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

BrokenPipeError: [Errno 32] Broken pipe

**Comment by JoHof** [comment]
Hi

hard to say. Can you let me know some things?

what is the dimensionality of input image.... input_image.GetSize()?

try to set num_workers=0 in line 58 of the file "C:\Users\Anaconda3\lib\site-packages\lungmask\mask.py" and then let me know how the error changed

best Jo

**Comment by hrktkhs** [comment]
Hello, Jo

Thank you very much for your help- It works!
 
input_image = sitk.GetImageFromArray(img3d)
segmentation = mask.apply(input_image)  # default model is U-net(R231)

Out[]:INFO:root:No GPU support available, will use CPU. Note, that this is significantly slower!
100%|██████████| 102/102 [02:30<00:00,  1.48s/it]
0it [00:00, ?it/s]

However, there is another problem- the created mask has no value. 
Input image is 3D and is converted from the array with values

sum(sum(sum(segmentation)))
Out[]: 0

input_image.GetSize()
Out[]: (512, 512, 102)

sum(sum(sum(img3d)))
Out[35]: 15617370

Could you find out the cause of this problem?

Thanks 

Hiro

**Comment by JoHof** [comment]
alright, is the image correctly encoded in hounsfield units? So are areas with air around -1000 and bones >1000?

**Comment by hrktkhs** [comment]
Thank you! It works!
