### ISSUE TITLE
SError: [Errno 24] Too many open files when applying lung mask on many DICOM images in a directory

### ISSUE THREAD

**Issue by ethanmoyer** [JoHof/lungmask#60]
Hello,

I have been using lungmask to segment CT images as a part of a radiogenomics project through my organization. We have a big data set with 130 patients where each patient has 256 DICOM images. We were really excited to use your tool because it will automate a lot of the segmentation we would have otherwise had to do. However, recently I stumbled on the following bug after many calls to lungmask.mask.apply.

SError: [Errno 24] Too many open files 

I'm unsure of whether there are open file handles in the software or whether I'm doing something incorrectly. In order to reproduce this bug, you have to apply this to over 200 files consecutively. I realize this takes a while to do, so I was just wondering whether this error has ever come up on your side when developing this software. 

If you need more information from me, please let me know.

**Comment by JoHof** [comment]
Hi Ethan,

you are the first reporting and issue with open file handles. I would suspect the the files are opened (and not closed) somewhere else in you code. How do you load your dicoms?

**Comment by ethanmoyer** [comment]
Thank you for getting back to me. I thought that might be the case at first but was unsure. Below is a short function that I wrote to use SimpleITK to read and write the files. From a brief look around documentation and examples, I couldn't find instances of SimpleITK needing to release its file handles, so I thought that was strange. 

from lungmask import mask
import SimpleITK as sitk
import os

```
def segmentLungs(imagepath):
	segimagepath = os.path.join(os.path.split(imagepath)[0], 'seg_' + os.path.split(imagepath)[1].split('.')[0]) + '.dcm'
	if os.path.isfile(segimagepath):
		segmentation = sitk.ReadImage(segimagepath)
	else:
		pixel_array = sitk.ReadImage(imagepath)
		segmentation = mask.apply(pixel_array)
		segmentation = sitk.GetImageFromArray(segmentation)  
		sitk.WriteImage(segmentation, segimagepath)
	return segmentation
```

And here is the traceback:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/ethanmoyer/miniconda3/lib/python3.9/site-packages/lungmask/mask.py", line 68, in apply
    for X in tqdm(dataloader_val):
  File "/Users/ethanmoyer/miniconda3/lib/python3.9/site-packages/tqdm/std.py", line 1167, in __iter__
    for obj in iterable:
  File "/Users/ethanmoyer/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/Users/ethanmoyer/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/Users/ethanmoyer/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/Users/ethanmoyer/miniconda3/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/ethanmoyer/miniconda3/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/ethanmoyer/miniconda3/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/ethanmoyer/miniconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/ethanmoyer/miniconda3/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/ethanmoyer/miniconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 58, in _launch
    self.pid = util.spawnv_passfds(spawn.get_executable(),
  File "/Users/ethanmoyer/miniconda3/lib/python3.9/multiprocessing/util.py", line 450, in spawnv_passfds
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files

Do you use this package or do you rely on something else?

**Comment by JoHof** [comment]
Hi,

ok. I see nothing wrong there. Maybe the dataloader is spilling open file handlers. Seems like there was a bug in pytorch once. Can you try to uninstall lungmask `pip uninstall lungmask` and install again `pip install git+https://github.com/JoHof/lungmask`? This might eventually fix the problem because we made a minor change a few weeks ago that should prevent pytorch from starting workers.

**Comment by ethanmoyer** [comment]
I've been running it all morning and I haven't run into that bug after reinstalling it. Thank you!

**Comment by JoHof** [comment]
Hi Ethan,

super. As far as I understand your code, you apply the lung segmentation individually on each slice (dicom file). I would recommend to load the whole series (e.g. with the sitk  [image series reader](https://simpleitk.readthedocs.io/en/master/link_DicomSeriesReader_docs.html)) and apply the lung segmentation on the volume. This is 1.) faster and 2.) there will be a proper postprocessing that removes smaller detections outside the lung... so eventually better quality
